app:
  image: redbadger/website-next
  ports:
    - "8000:8000"
  environment:
    - WORKABLE_KEY=${WORKABLE_KEY}
    - DB_USERNAME=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}
proxy:
  image: redbadger/website-next-proxy
  ports:
    - "80:80"
  environment:
    - APP_HOST=${APP_HOST}
    - APP_PORT=8000
